menu:
    Infra DX Blog: /
    Archive: /archives/
    Github: https://github.com/lystable/infra-dx-blog

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
